version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ghcr.io/xxubin04/todak-for-daily/todak-backend:latest
    container_name: todak-server
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      FIREBASE_CONFIG_PATH: /app/firebase/serviceAccountKey.json
    volumes:
       - ./firebase/serviceAccountKey.json:/app/firebase/serviceAccountKey.json

volumes:
  db_data:
