spring:
  application:
    name: todak-server
  profiles:
    active: dev
    include: secret
firebase:
  config:
    path: classpath:firebase/serviceAccountKey.json
env:
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}