spring:
  application:
    name: todak-server
  profiles:
    active: secret
firebase:
  config:
    path: classpath:firebase/serviceAccountKey.json
  storage:
    bucket: todak-for-daily.firebasestorage.app